#!/usr/bin/env sh
# shellcheck disable=SC1090
. "./client/$(dirname -- "$0")/_/husky.sh"


# shellcheck disable=SC2164
cd client
npm run lint-front
npm test
npx eslint "**/*.js" "**/*.jsx" --fix
npx stylelint "**/*.scss" "**/*.css" --fix
npx prettier "**/*.js" "**/*.jsx" --write
